version: '2'
services:
  mysql:
    image: 'mysql:5.7'
    environment:
      - MYSQL_DATABASE=dihlab
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    restart: always
    ports:
      - '127.0.0.1:3306:3306'
    volumes:
      - 'mysql:/var/lib/mysql'

  web:
    build: .
    ports:
      - '127.0.0.1:8000:8000'
      - '0.0.0.0:80:8000'
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      - ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=dihlab
      - DB_USER=root
      - DB_PASSWORD=
    restart: on-failure:10
    # volumes:
    #   - .:/app

volumes:
  mysql:
