# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 20:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desserts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='owner',
            field=models.ForeignKey(help_text='The user has the item on own cart', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='calories',
            field=models.IntegerField(help_text='Number of calories the dessert provides'),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='description',
            field=models.CharField(blank=True, help_text='Dessert description', max_length=500),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='image',
            field=models.ImageField(help_text='Dessert shown image', upload_to='dessert_imgs/'),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='name',
            field=models.CharField(help_text='Dessert shown name', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='cart_items',
            field=models.ManyToManyField(help_text='Items this user has in the cart', through='desserts.CartItem', to='desserts.Dessert'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_guest',
            field=models.BooleanField(default=False, help_text='Gust account? default is false', verbose_name='Guest'),
        ),
    ]
