# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 14:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desserts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessert',
            name='calories',
            field=models.IntegerField(help_text='Number of calories the dessert provides', validators=[django.core.validators.MinValueValidator(0, message="Calories can't be below 0")]),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Dessert price', max_digits=9, validators=[django.core.validators.MinValueValidator(0, message="Price can't be below 0")]),
        ),
    ]
