# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desserts', '0002_auto_20180131_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessert',
            name='description',
            field=models.CharField(blank=True, help_text='Dessert description. [Optional]', max_length=500),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='image',
            field=models.ImageField(help_text='Shown image', upload_to='desserts/'),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='name',
            field=models.CharField(help_text='Shown name', max_length=50),
        ),
    ]
